"""Episode-aware, read-only storage for direct NFS access.

This module is the storage primitive for ``encoded_train_v2``.  It deliberately
does not know about YARR, model checkpoints, or FilterCorrection state.  The
writer stores immutable episode payloads in a small number of length-prefixed
chunk files; the reader keeps chunk descriptors open and uses positional reads
so a worker never scans or opens one file per transition.

The payload is trusted, model-facing data produced by a future v2 encoder.  It
must contain observations/actions and episode markers, but must not contain a
learned hidden state or posterior generated by a particular checkpoint.
"""

from __future__ import annotations

import hashlib
import json
import os
import pickle
import struct
from collections import OrderedDict, defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple


FORMAT_NAME = "bridgevla_episode_store"
FORMAT_VERSION = 1
_LENGTH = struct.Struct(">Q")


def _sha256(path: Path, block_size: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            block = handle.read(block_size)
            if not block:
                break
            digest.update(block)
    return digest.hexdigest()


class EpisodeStoreWriter:
    """Write complete episodes into immutable chunk files.

    The destination may be on NFS.  A temporary directory is populated first,
    then atomically renamed into place; readers never observe a half-written
    manifest.  ``max_chunk_bytes`` is a layout knob, not a semantic one.
    """

    def __init__(
        self,
        destination: str | os.PathLike[str],
        *,
        split: str,
        max_chunk_bytes: int = 512 * 1024 * 1024,
        schema: Optional[Mapping[str, object]] = None,
        source: Optional[Mapping[str, object]] = None,
    ) -> None:
        if not split:
            raise ValueError("split must be non-empty")
        if int(max_chunk_bytes) < 1:
            raise ValueError("max_chunk_bytes must be positive")
        self.destination = Path(destination).expanduser()
        self.split = str(split)
        self.max_chunk_bytes = int(max_chunk_bytes)
        self.schema = dict(schema or {})
        self.source = dict(source or {})
        self._temporary = self.destination.with_name(
            f".{self.destination.name}.building-{os.getpid()}"
        )
        if self._temporary.exists():
            raise FileExistsError(
                f"temporary episode store already exists: {self._temporary}"
            )
        self._chunks_dir = self._temporary / "chunks"
        self._chunks_dir.mkdir(parents=True, exist_ok=False)
        self._handle = None
        self._chunk_name: Optional[str] = None
        self._chunk_bytes = 0
        self._chunk_specs: List[Dict[str, object]] = []
        self._tasks: Dict[str, Dict[str, object]] = defaultdict(
            lambda: {"episodes": []}
        )
        self._closed = False

    def _open_chunk(self) -> None:
        if self._handle is not None:
            self._close_chunk()
        index = len(self._chunk_specs)
        name = f"chunk-{index:06d}.bin"
        path = self._chunks_dir / name
        self._handle = path.open("wb")
        self._chunk_name = name
        self._chunk_bytes = 0

    def _close_chunk(self) -> None:
        if self._handle is None or self._chunk_name is None:
            return
        handle = self._handle
        handle.flush()
        os.fsync(handle.fileno())
        handle.close()
        path = self._chunks_dir / self._chunk_name
        self._chunk_specs.append(
            {
                "file": f"chunks/{self._chunk_name}",
                "bytes": int(path.stat().st_size),
                "sha256": _sha256(path),
            }
        )
        self._handle = None
        self._chunk_name = None
        self._chunk_bytes = 0

    def add_episode(
        self,
        task: str,
        episode_id: int | str,
        payload: Mapping[str, object],
        *,
        valid_length: Optional[int] = None,
    ) -> None:
        if self._closed:
            raise RuntimeError("cannot add an episode after finalize")
        task = str(task)
        if not task:
            raise ValueError("task must be non-empty")
        if task in self._tasks and any(
            item["episode_id"] == str(episode_id)
            for item in self._tasks[task]["episodes"]
        ):
            raise ValueError(f"duplicate episode id: task={task}, id={episode_id}")
        encoded = pickle.dumps(dict(payload), protocol=5)
        record_bytes = _LENGTH.size + len(encoded)
        if self._handle is None:
            self._open_chunk()
        if self._chunk_bytes and self._chunk_bytes + record_bytes > self.max_chunk_bytes:
            self._open_chunk()
        assert self._handle is not None
        assert self._chunk_name is not None
        offset = int(self._handle.tell()) + _LENGTH.size
        self._handle.write(_LENGTH.pack(len(encoded)))
        self._handle.write(encoded)
        self._chunk_bytes += record_bytes
        if valid_length is None:
            inferred = payload.get("valid_length")
            valid_length = int(inferred) if inferred is not None else 0
        if int(valid_length) < 1:
            raise ValueError(
                f"valid_length must be positive: task={task}, id={episode_id}"
            )
        self._tasks[task]["episodes"].append(
            {
                "episode_id": str(episode_id),
                "chunk": len(self._chunk_specs),
                "offset": offset,
                "length": len(encoded),
                "valid_length": int(valid_length),
            }
        )

    def finalize(self) -> Dict[str, object]:
        if self._closed:
            raise RuntimeError("episode store writer is already closed")
        self._close_chunk()
        tasks = {
            task: {
                "episode_count": len(spec["episodes"]),
                "episodes": list(spec["episodes"]),
            }
            for task, spec in sorted(self._tasks.items())
        }
        manifest: Dict[str, object] = {
            "format": FORMAT_NAME,
            "version": FORMAT_VERSION,
            "split": self.split,
            "schema": self.schema,
            "source": self.source,
            "chunks": self._chunk_specs,
            "tasks": tasks,
        }
        manifest_path = self._temporary / "manifest.json"
        with manifest_path.open("w", encoding="utf-8") as handle:
            json.dump(manifest, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        if self.destination.exists():
            raise FileExistsError(
                f"refusing to replace existing episode store: {self.destination}"
            )
        os.replace(self._temporary, self.destination)
        self._closed = True
        return manifest

    def abort(self) -> None:
        if self._closed:
            return
        if self._handle is not None:
            self._handle.close()
            self._handle = None
        import shutil

        shutil.rmtree(self._temporary, ignore_errors=True)
        self._closed = True


class EpisodeStoreReader:
    """Read episodes from a v2 store using persistent NFS file descriptors."""

    def __init__(
        self,
        root: str | os.PathLike[str],
        *,
        expected_split: Optional[str] = None,
        cache_episodes: int = 2,
        verify_chunks: bool = False,
    ) -> None:
        if int(cache_episodes) < 0:
            raise ValueError("cache_episodes must be non-negative")
        self.root = Path(root).expanduser().resolve()
        manifest_path = self.root / "manifest.json"
        with manifest_path.open("r", encoding="utf-8") as handle:
            manifest = json.load(handle)
        if manifest.get("format") != FORMAT_NAME:
            raise ValueError(f"unsupported episode store format: {manifest.get('format')!r}")
        if int(manifest.get("version", -1)) != FORMAT_VERSION:
            raise ValueError(f"unsupported episode store version: {manifest.get('version')!r}")
        split = str(manifest.get("split", ""))
        if expected_split is not None and split != str(expected_split):
            raise ValueError(f"episode store split mismatch: expected={expected_split!r}, got={split!r}")
        self.manifest = manifest
        self.split = split
        self.schema = manifest.get("schema", {})
        self.source = manifest.get("source", {})
        self._chunks = list(manifest.get("chunks", []))
        self._tasks = dict(manifest.get("tasks", {}))
        self._fds: "OrderedDict[int, int]" = OrderedDict()
        self._cache_limit = int(cache_episodes)
        self._episode_cache: "OrderedDict[Tuple[str, str], Mapping[str, object]]" = OrderedDict()
        self._verify_chunks = bool(verify_chunks)
        self._verified_chunks = set()
        self._read_count = 0
        self._read_bytes = 0
        self._chunk_open_count = 0
        if not self._tasks:
            raise ValueError("episode store has no tasks")
        for task, spec in self._tasks.items():
            episodes = spec.get("episodes", [])
            if int(spec.get("episode_count", -1)) != len(episodes):
                raise ValueError(f"episode count mismatch for task={task}")
            for episode in episodes:
                chunk = int(episode["chunk"])
                if chunk < 0 or chunk >= len(self._chunks):
                    raise ValueError(f"invalid chunk index for task={task}")
                if int(episode["offset"]) < 0 or int(episode["length"]) < 1:
                    raise ValueError(f"invalid episode range for task={task}")

    @property
    def task_names(self) -> List[str]:
        return sorted(self._tasks)

    def episode_ids(self, task: str) -> List[str]:
        spec = self._tasks.get(str(task))
        if spec is None:
            raise KeyError(f"unknown task: {task}")
        return [str(item["episode_id"]) for item in spec["episodes"]]

    def _episode_spec(self, task: str, episode_id: int | str) -> Mapping[str, object]:
        task = str(task)
        target = str(episode_id)
        spec = self._tasks.get(task)
        if spec is None:
            raise KeyError(f"unknown task: {task}")
        for episode in spec["episodes"]:
            if str(episode["episode_id"]) == target:
                return episode
        raise KeyError(f"unknown episode: task={task}, id={episode_id}")

    def _fd_for_chunk(self, chunk: int) -> int:
        fd = self._fds.pop(chunk, None)
        if fd is not None:
            self._fds[chunk] = fd
            return fd
        path = self.root / str(self._chunks[chunk]["file"])
        fd = os.open(path, os.O_RDONLY)
        self._chunk_open_count += 1
        self._fds[chunk] = fd
        # A small FD cache is enough: episodes are grouped by chunk by the
        # sampler, and keeping it bounded avoids leaking descriptors in workers.
        while len(self._fds) > 8:
            _, old_fd = self._fds.popitem(last=False)
            os.close(old_fd)
        return fd

    def _verify_chunk(self, chunk: int) -> None:
        if not self._verify_chunks or chunk in self._verified_chunks:
            return
        path = self.root / str(self._chunks[chunk]["file"])
        expected = str(self._chunks[chunk].get("sha256", ""))
        if expected and _sha256(path) != expected:
            raise IOError(f"episode chunk hash mismatch: {path}")
        self._verified_chunks.add(chunk)

    @staticmethod
    def _pread_exact(fd: int, offset: int, length: int) -> bytes:
        data = bytearray()
        cursor = int(offset)
        remaining = int(length)
        while remaining:
            block = os.pread(fd, remaining, cursor)
            if not block:
                raise IOError(
                    f"short read from episode chunk: offset={offset}, length={length}, "
                    f"received={len(data)}"
                )
            data.extend(block)
            cursor += len(block)
            remaining -= len(block)
        return bytes(data)

    def read_episode(self, task: str, episode_id: int | str) -> Mapping[str, object]:
        key = (str(task), str(episode_id))
        cached = self._episode_cache.pop(key, None)
        if cached is not None:
            self._episode_cache[key] = cached
            return cached
        spec = self._episode_spec(*key)
        chunk = int(spec["chunk"])
        self._verify_chunk(chunk)
        fd = self._fd_for_chunk(chunk)
        encoded = self._pread_exact(fd, int(spec["offset"]), int(spec["length"]))
        self._read_count += 1
        self._read_bytes += len(encoded)
        payload = pickle.loads(encoded)
        if not isinstance(payload, Mapping):
            raise ValueError(f"episode payload is not a mapping: {key}")
        if self._cache_limit:
            self._episode_cache[key] = payload
            while len(self._episode_cache) > self._cache_limit:
                self._episode_cache.popitem(last=False)
        return payload

    def read_batch(
        self, references: Sequence[Tuple[str, int | str]]
    ) -> List[Mapping[str, object]]:
        """Read a batch while grouping references by chunk without reordering it."""
        grouped: Dict[int, List[Tuple[int, Tuple[str, str]]]] = defaultdict(list)
        keys = [(str(task), str(episode_id)) for task, episode_id in references]
        for position, key in enumerate(keys):
            spec = self._episode_spec(*key)
            grouped[int(spec["chunk"])].append((position, key))
        result: List[Optional[Mapping[str, object]]] = [None] * len(keys)
        for chunk in sorted(grouped):
            # Opening and reading in chunk order improves NFS locality while
            # restoring the caller's order before the batch reaches the model.
            for position, key in sorted(
                grouped[chunk],
                key=lambda item: int(self._episode_spec(*item[1])["offset"]),
            ):
                result[position] = self.read_episode(*key)
        return [item for item in result if item is not None]

    @property
    def stats(self) -> Mapping[str, int]:
        return {
            "episode_reads": int(self._read_count),
            "payload_bytes": int(self._read_bytes),
            "chunk_opens": int(self._chunk_open_count),
            "cache_entries": len(self._episode_cache),
        }

    def close(self) -> None:
        for fd in self._fds.values():
            os.close(fd)
        self._fds.clear()
        self._episode_cache.clear()

    def __enter__(self) -> "EpisodeStoreReader":
        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        self.close()
